### ISSUE TITLE
end this project

### ISSUE THREAD

**Issue by vistafan12** [Igoorx/osuBancho#4]
pls

**Comment by insomnyawolf** [comment]
i was thinking on do shit therebut my knowledge at c# is very limited. can you help to the project too @vistafan12

**Comment by vistafan12** [comment]
yes, i can help on this project

**Comment by Igoorx** [comment]
I do not see why this project should be ended, since, at the time I did it, was because it was the only way to have an "full" osu server, but as the source of the bancho leaked, and now maybe have more options on internet, it is no longer the only way..
